<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Mission</name>
   <tag></tag>
   <elementGuidId>07b29975-512c-4482-b0ef-156609fc8fa5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>dt:nth-of-type(2) > a.ckeditor-accordion-toggler</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-daudo-subtheme-content']/div/article/div/div[2]/div/dl/dt[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Mission&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c5e14d24-cca9-4daa-8c94-d7b37077d905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ckeditor-accordion-toggler</value>
      <webElementGuid>5474aec0-e3fc-4686-b4b1-035ca36be286</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8a5d418f-d152-4122-93ef-f33d63cb97b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mission</value>
      <webElementGuid>f6e4e189-91d5-4808-abc5-824dabd1900e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-daudo-subtheme-content&quot;)/div[@class=&quot;content block-content&quot;]/article[@class=&quot;node node--type-main-page node--promoted node--view-mode-full clearfix&quot;]/div[@class=&quot;node__content clearfix&quot;]/div[@class=&quot;field field--name-body field--type-text-with-summary field--label-hidden field__item&quot;]/div[@class=&quot;ckeditor-accordion-container&quot;]/dl[@class=&quot;styled&quot;]/dt[2]/a[@class=&quot;ckeditor-accordion-toggler&quot;]</value>
      <webElementGuid>5cb55836-62aa-4bc8-9823-0032f011b281</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-daudo-subtheme-content']/div/article/div/div[2]/div/dl/dt[2]/a</value>
      <webElementGuid>a57f558f-0ecc-4c10-bf12-e19a2de55da1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Mission')])[2]</value>
      <webElementGuid>cff0c25f-0632-4e7d-9ecb-c495311470ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campus Walk'])[1]/following::a[2]</value>
      <webElementGuid>cd89a21c-f3cf-48b7-b88e-5fafd47d7d14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vision &amp; Mission'])[2]/following::a[3]</value>
      <webElementGuid>86da5763-1889-49dd-8f4b-5e839c142e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To inculcate in students a global vision with skills of international competence.'])[1]/preceding::a[1]</value>
      <webElementGuid>df76368c-f198-4c5f-aa5d-a68811b4ef6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='University'])[1]/preceding::a[1]</value>
      <webElementGuid>8148c8aa-e337-4678-b02a-4b0f56d57a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mission']/parent::*</value>
      <webElementGuid>5c2b334b-a5c0-4953-97ab-a8e0ad41e787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[6]</value>
      <webElementGuid>5a7d7993-53b2-4ce5-a4cc-a973c6483cac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dt[2]/a</value>
      <webElementGuid>b427b734-8673-4b5d-b103-abe032562f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Mission' or . = 'Mission')]</value>
      <webElementGuid>161d5314-8ba0-4c48-ac75-324f880e9b8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
