<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Vision  Mission</name>
   <tag></tag>
   <elementGuidId>9ef7116e-b924-4084-b9a9-1f3261042f36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='block-universitymenu']/div/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Vision &amp; Mission &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eb21bb49-2ae2-4408-8c87-5f8de751a974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/273/vision-mission</value>
      <webElementGuid>091674ff-c7c9-47f4-bfa0-3c1b974250e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gva_layout</name>
      <type>Main</type>
      <value>menu-list</value>
      <webElementGuid>d42d9571-7154-4b2e-86bb-35de99af3dfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gva_layout_columns</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>2356b138-78f6-4e40-b944-bd65fd715dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gva_block</name>
      <type>Main</type>
      <value>75independenceday</value>
      <webElementGuid>d2260056-9714-42c9-b34b-401a03daf9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gva_block_en</name>
      <type>Main</type>
      <value>75independenceday</value>
      <webElementGuid>10e8a23e-c02e-474a-8683-ee80ae6d4d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gva_block_ta</name>
      <type>Main</type>
      <value>75independenceday</value>
      <webElementGuid>2d736315-f5c4-49e1-a8f4-6ee600b1d55a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-drupal-link-system-path</name>
      <type>Main</type>
      <value>node/2791</value>
      <webElementGuid>e94823d1-ac2c-488a-a4f4-417f196b13ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vision &amp; Mission</value>
      <webElementGuid>cb3156f4-9005-4d39-9877-9501535807ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-universitymenu&quot;)/div[@class=&quot;block-content&quot;]/ul[@class=&quot;gva_menu&quot;]/li[@class=&quot;menu-item&quot;]/a[1]</value>
      <webElementGuid>3885ab3a-9da4-4f76-a8d1-8c9bac2b7b91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='block-universitymenu']/div/ul/li[2]/a</value>
      <webElementGuid>32e5891e-3a66-462e-bd4a-971c8663be12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Vision &amp; Mission')]</value>
      <webElementGuid>8dedfaa9-0154-4fc0-8dcc-71dd8a7b4814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About University'])[1]/following::a[1]</value>
      <webElementGuid>5faa1d54-1f10-44b7-ac25-fa46a93ff2a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='University menu'])[1]/following::a[2]</value>
      <webElementGuid>5f517dc6-6492-47f2-b9e3-c55cf1a90471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acts &amp; Statues'])[1]/preceding::a[1]</value>
      <webElementGuid>28cc2ff1-4b13-4822-bb0e-0aacf1399ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organogram'])[1]/preceding::a[2]</value>
      <webElementGuid>83e8b001-4dae-4c23-9a90-af44a3730393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vision &amp; Mission']/parent::*</value>
      <webElementGuid>fe6300bc-8b34-44fa-b631-b73ac169a56c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/273/vision-mission')]</value>
      <webElementGuid>afefd5f3-0133-40bd-84c5-3d6f8516c3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div/ul/li[2]/a</value>
      <webElementGuid>003c73ef-6f6f-4844-85e9-33e01bb3f930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/273/vision-mission' and (text() = 'Vision &amp; Mission' or . = 'Vision &amp; Mission')]</value>
      <webElementGuid>4236fde4-0dc0-429c-939c-cb68a72431c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
