<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Notification for IIPM and YGEN Students_110091</name>
   <tag></tag>
   <elementGuidId>def5b1be-466c-47a2-8b45-91dcd8733cd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.tp-leftarrow.tparrows.zeus.noSwipe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='revslider-128']/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.tp-leftarrow</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7fcafe43-205c-47ee-b76b-6cfca5f9f61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tp-leftarrow tparrows zeus  noSwipe</value>
      <webElementGuid>d3fe873a-d37c-4e17-9cff-d4ce12d435ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;revslider-128&quot;)/div[@class=&quot;tp-leftarrow tparrows zeus  noSwipe&quot;]</value>
      <webElementGuid>6875edb5-3ef9-4bf3-b521-6f3785300b7d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='revslider-128']/div[3]</value>
      <webElementGuid>24ece702-aecd-4779-b1e8-2f4f0cbdecb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Notification for IIPM and YGEN Students to receive Certificates'])[1]/following::div[19]</value>
      <webElementGuid>ae657753-3fa7-486c-b439-9852d459ec34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Table - April 2024 Examinations'])[1]/following::div[19]</value>
      <webElementGuid>b24108b6-0063-472c-a07d-6872f8d892fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slide 1'])[1]/preceding::div[6]</value>
      <webElementGuid>1ab92207-83ea-4397-aa40-d1874343d3a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Slide 2'])[1]/preceding::div[7]</value>
      <webElementGuid>0c07263d-1d8f-4e68-815d-897072e5d8aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]</value>
      <webElementGuid>7ce99daa-84a5-4aca-ab76-be68b9b07765</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
