<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_130,993</name>
   <tag></tag>
   <elementGuidId>18dae954-8916-416a-92d0-449a17a403a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[2]/section[6]/div/div/div[2]/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;130,993&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>70fc149f-af1e-4bcd-838b-fe38ff84e868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-animation-duration</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>570c8de4-7308-4ba4-978f-334c86765a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>130993</value>
      <webElementGuid>ba96c3cc-b94a-41b0-bb3e-42e5446a7932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>animate-number text-white mt-0 font-38 font-weight-500 appeared</value>
      <webElementGuid>aff769d4-a9bd-41dd-b4c5-b54e60d66d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>130,993</value>
      <webElementGuid>b4c18e3d-7924-4c58-b014-160c6e6601bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;main-content&quot;]/section[@class=&quot;divider parallax layer-overlay&quot;]/div[@class=&quot;container pt-70 pb-60&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-6 col-md-3 mb-md-50&quot;]/div[@class=&quot;funfact text-center&quot;]/h4[@class=&quot;animate-number text-white mt-0 font-38 font-weight-500 appeared&quot;]</value>
      <webElementGuid>899cd10c-4c94-4506-9edc-f9145ef19297</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/section[6]/div/div/div[2]/div/h4</value>
      <webElementGuid>9df933e0-6614-4431-b8ba-b616ef91fdd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Affiliated Colleges'])[2]/following::h4[1]</value>
      <webElementGuid>80b15150-58e9-4362-8b5a-ee258ca4ca20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read more'])[5]/following::h4[2]</value>
      <webElementGuid>13ee8f3b-cd74-455f-b7f8-c200b8c18232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Affiliated College Students'])[1]/preceding::h4[1]</value>
      <webElementGuid>c41c6446-33db-40ca-8ace-afc456f94ad8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='University Departments'])[1]/preceding::h4[2]</value>
      <webElementGuid>d3b1ed92-c14d-4c2e-aaff-50a3f9bdf627</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='130,993']/parent::*</value>
      <webElementGuid>d0b92a2d-bdfe-4e94-8d57-529696e7bc4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/h4</value>
      <webElementGuid>e85cb31c-e473-457f-b107-97800ec683d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = '130,993' or . = '130,993')]</value>
      <webElementGuid>db1b22c9-78ec-4b11-9399-4c9f79d85351</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
