<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Read more_fa fa-users mt-5 text-white</name>
   <tag></tag>
   <elementGuidId>1f591156-e237-4ba6-90a0-28992997b952</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-users.mt-5.text-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[2]/section[6]/div/div/div/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>section >> internal:has-text=&quot;108 Affiliated Colleges 130,993 Affiliated College Students 29 University Depart&quot;i >> i >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>d696845d-9abe-4eb4-ab07-a7e34fed6a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-users mt-5 text-white</value>
      <webElementGuid>f318a94b-6e0d-4090-8f28-2b7193f6f461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;main-content&quot;]/section[@class=&quot;divider parallax layer-overlay&quot;]/div[@class=&quot;container pt-70 pb-60&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-6 col-md-3 mb-md-50&quot;]/div[@class=&quot;funfact text-center&quot;]/i[@class=&quot;fa fa-users mt-5 text-white&quot;]</value>
      <webElementGuid>3d5f5f3f-ab13-41d4-98f6-c9c7c5570100</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/section[6]/div/div/div/div/i</value>
      <webElementGuid>25a2c0d2-cfb8-4217-affd-16e22a2062f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[6]/div/div/div/div/i</value>
      <webElementGuid>d1b70cf9-9e23-445e-9fa7-cba32edf453d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
