<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_View Details_img-responsive img-fullwid_322ea2</name>
   <tag></tag>
   <elementGuidId>2f57eca5-a990-4745-b4c0-0d6237f927f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-responsive.img-fullwidth.mt-10.ml-30.ml-xs-0.ml-sm-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='about']/div/div/div/div[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#about img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f19cdf5c-d8a3-4f44-985e-8512a6e6bab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>images/about/5.jpg</value>
      <webElementGuid>d762d64d-432f-43c9-b656-a5a1873e34df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-responsive img-fullwidth mt-10 ml-30 ml-xs-0 ml-sm-0</value>
      <webElementGuid>280cf172-7e0f-4fcb-92ba-3af49450b09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;about&quot;)/div[@class=&quot;container mt-0 pb-70 pt-0&quot;]/div[@class=&quot;section-content&quot;]/div[@class=&quot;row mt-10&quot;]/div[@class=&quot;col-sm-12 col-md-6 mt-0 wow fadeInDown&quot;]/div[@class=&quot;video-popup&quot;]/img[@class=&quot;img-responsive img-fullwidth mt-10 ml-30 ml-xs-0 ml-sm-0&quot;]</value>
      <webElementGuid>cbdb8051-2129-4a97-8785-9c0b3ea1bcc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='about']/div/div/div/div[2]/div/img</value>
      <webElementGuid>48a76ad1-d94c-47aa-9e36-13f58e832979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>eb26f5fa-1d72-4763-9aa3-75386928fa84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'images/about/5.jpg']</value>
      <webElementGuid>1e2781b3-0256-46a6-8ea5-6de7202cba15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
