<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Bestow globally comparable quality educat_2b3ef6</name>
   <tag></tag>
   <elementGuidId>529e0f6f-f5e8-40b0-ae37-e906f721c46f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.text-align-justify</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='block-daudo-subtheme-content']/div/article/div/div[2]/div/dl/dd/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Bestow globally comparable quality education on youth, embodied with character b&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>7e18e601-7851-47eb-b232-6f8a078aaf2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-align-justify</value>
      <webElementGuid>1e1affdd-e37b-4bf0-97b7-ed30fdfa46c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bestow globally comparable quality education on youth, embodied with character building, to invoke the University's motto “Educate to Elevate” and uphold the secular ideals of the nation as envisioned by Mahakavi Subramania Bharathiar.</value>
      <webElementGuid>90de2125-d823-4ba6-980f-894ed041f701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-daudo-subtheme-content&quot;)/div[@class=&quot;content block-content&quot;]/article[@class=&quot;node node--type-main-page node--promoted node--view-mode-full clearfix&quot;]/div[@class=&quot;node__content clearfix&quot;]/div[@class=&quot;field field--name-body field--type-text-with-summary field--label-hidden field__item&quot;]/div[@class=&quot;ckeditor-accordion-container&quot;]/dl[@class=&quot;styled&quot;]/dd[@class=&quot;active&quot;]/p[@class=&quot;text-align-justify&quot;]</value>
      <webElementGuid>124cec8b-fedf-4882-abad-b12bb0c9f7a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-daudo-subtheme-content']/div/article/div/div[2]/div/dl/dd/p</value>
      <webElementGuid>433303fe-ad97-49d1-b85e-9dee9e41b7d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Campus Walk'])[1]/following::p[1]</value>
      <webElementGuid>404cdf5e-fbb5-4237-af22-4c5408c4694d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vision &amp; Mission'])[2]/following::p[1]</value>
      <webElementGuid>d8fae11a-ec2b-4c73-83e4-3a043ba04aff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To inculcate in students a global vision with skills of international competence.'])[1]/preceding::p[1]</value>
      <webElementGuid>bbe2078b-4a6e-4b69-be3c-9214b75c3110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='University'])[1]/preceding::p[2]</value>
      <webElementGuid>0f2308bc-872d-42b9-b329-71320365f4d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//dd/p</value>
      <webElementGuid>ef1b6d45-3275-41f9-a5f4-ed6deb3ce611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = concat(&quot;Bestow globally comparable quality education on youth, embodied with character building, to invoke the University&quot; , &quot;'&quot; , &quot;s motto “Educate to Elevate” and uphold the secular ideals of the nation as envisioned by Mahakavi Subramania Bharathiar.&quot;) or . = concat(&quot;Bestow globally comparable quality education on youth, embodied with character building, to invoke the University&quot; , &quot;'&quot; , &quot;s motto “Educate to Elevate” and uphold the secular ideals of the nation as envisioned by Mahakavi Subramania Bharathiar.&quot;))]</value>
      <webElementGuid>1b6f4e78-1695-4210-b759-944033748963</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
