<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_It is Named after the renowned Tamil Poet_903f81</name>
   <tag></tag>
   <elementGuidId>25af63dc-77f3-49a1-8127-2aac61d3e705</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.mb-15</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='about']/div/div/div/div/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;It is Named after the renowned Tamil Poet scholar, Professor P. Sundaram Pillai &quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>be47f91c-6c2f-4d01-9a35-41bf689c7c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mb-15</value>
      <webElementGuid>b9c1fe1b-fd35-48a4-87a2-7f14eefa9be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>It is Named after the renowned Tamil Poet scholar, Professor P. Sundaram Pillai (1855-1897), the author of the famous verse drama Manonmaniam. It is his poem that has become “Tamil Thaai Vazhthu” the official invocation song sung in all functions in Tamilnadu.</value>
      <webElementGuid>799c577d-b5c7-4438-bdca-f86068598546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;about&quot;)/div[@class=&quot;container mt-0 pb-70 pt-0&quot;]/div[@class=&quot;section-content&quot;]/div[@class=&quot;row mt-10&quot;]/div[@class=&quot;col-sm-12 col-md-6 mb-sm-20 wow fadeInUp&quot;]/p[@class=&quot;mb-15&quot;]</value>
      <webElementGuid>13669f53-a82f-43dc-ae81-50d5630729ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='about']/div/div/div/div/p[2]</value>
      <webElementGuid>b631aa70-fc3c-415a-b1ef-f001ab1f316c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manonmaniam Sundaranar University'])[2]/following::p[2]</value>
      <webElementGuid>f16ed5f9-008e-4be1-a21c-7014f9446f0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[1]/preceding::p[1]</value>
      <webElementGuid>6442af81-7d1f-4c8e-99e9-62e2d5313133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='It is Named after the renowned Tamil Poet scholar, Professor P. Sundaram Pillai (1855-1897), the author of the famous verse drama Manonmaniam. It is his poem that has become “Tamil Thaai Vazhthu” the official invocation song sung in all functions in Tamilnadu.']/parent::*</value>
      <webElementGuid>afdae969-cde0-4638-b8f1-68642101c8e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>1698db54-689c-45ca-8b1a-1391a3a2e573</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'It is Named after the renowned Tamil Poet scholar, Professor P. Sundaram Pillai (1855-1897), the author of the famous verse drama Manonmaniam. It is his poem that has become “Tamil Thaai Vazhthu” the official invocation song sung in all functions in Tamilnadu.' or . = 'It is Named after the renowned Tamil Poet scholar, Professor P. Sundaram Pillai (1855-1897), the author of the famous verse drama Manonmaniam. It is his poem that has become “Tamil Thaai Vazhthu” the official invocation song sung in all functions in Tamilnadu.')]</value>
      <webElementGuid>b37a5cb5-b5aa-4c73-b4f3-00047ea47423</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
